# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 301)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.find_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.find_edit.setGeometry(QtCore.QRect(130, 130, 113, 22))
        self.find_edit.setObjectName("find_edit")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(10, 60, 93, 28))
        self.start_button.setObjectName("start_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.label.setObjectName("label")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(120, 60, 93, 28))
        self.stop_button.setObjectName("stop_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 111, 21))
        self.label_2.setObjectName("label_2")
        self.find_button = QtWidgets.QPushButton(self.centralwidget)
        self.find_button.setGeometry(QtCore.QRect(10, 190, 101, 31))
        self.find_button.setObjectName("find_button")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(460, 220, 93, 28))
        self.close_button.setObjectName("close_button")
        self.plot = PlotWidget(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(290, 10, 261, 151))
        self.plot.setObjectName("plot")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 10, 111, 21))
        self.label_3.setObjectName("label_3")
        self.count_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.count_edit.setGeometry(QtCore.QRect(130, 160, 113, 22))
        self.count_edit.setObjectName("count_edit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 111, 21))
        self.label_4.setObjectName("label_4")
        self.cache_button = QtWidgets.QPushButton(self.centralwidget)
        self.cache_button.setGeometry(QtCore.QRect(130, 190, 101, 31))
        self.cache_button.setObjectName("cache_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Бот"))
        self.start_button.setText(_translate("MainWindow", "Старт"))
        self.label.setText(_translate("MainWindow", "Запуск бота"))
        self.stop_button.setText(_translate("MainWindow", "Стоп"))
        self.label_2.setText(_translate("MainWindow", "Название товара"))
        self.find_button.setText(_translate("MainWindow", "Поиск"))
        self.close_button.setText(_translate("MainWindow", "Закрыть"))
        self.label_3.setText(_translate("MainWindow", "Динамика цены"))
        self.label_4.setText(_translate("MainWindow", "Текущая цена"))
        self.cache_button.setText(_translate("MainWindow", "Очистить кэш"))
from pyqtgraph import PlotWidget
